### ISSUE TITLE
Local User Agent Detection Issue

### ISSUE THREAD

**Issue by djskripta** [HandsetDetection/laravel51-provider#1]
Looks like the library has issues parsing the user agent when using the local handset detection feature.

Here’s what we are using (which works via api call, but fails locally):

``` PHP
$hd = App('HandsetDetection'); 
$hd->deviceDetect(['user-agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B436 Safari/600.1.4']);
```

This fails with a 301 locally.. HDDevice:440 doesn’t find anything:

``` PHP
$_id = $this->getMatch('user-agent', $headers['user-agent'], DETECTIONV4_GENERIC, 'agent', 'device');
```

We have all of the supplied json files in the directory that the library is set up to pull from (`/home/***/***/storage/app/hd40store`) - but it’s not getting that far because of the issue above

Looping in @artkay @biteknight

**Comment by elricho** [comment]
Thanks for the report.

Is that issue appearing via artisan (cli) or in a web context ?
Is it possible there could be a permissions issue on the files or directory ?
- If cron is downloading the archive files might get different ownership to the web user (or cli user).
  Can you attach your handsetdetection.php config file (from laravel) without api credentials ?

I've attached two Command files I'm using for testing that might help validate your setup. Unzip and drop the files into app/Console/Commands, then run fetcharchive to download the archive & detect:devices to test a few different user-agents.

```
php artisan fetcharchive
php artisan detect:devices

```

[Archive.zip](https://github.com/HandsetDetection/laravel51-provider/files/322035/Archive.zip)

**Comment by djskripta** [comment]
Thanks for the response @elricho 
the `php artisan fetcharchive` command worked and retrieved an updated copy of the `ultimate` device database.

However, running `php artisan detect:devices` - even after a `chmod -R +7777 storage/app/hd40store` resulted in several of these:

`{"status":301,"message":"Not Found"}`

As for cron - for now, we are updating the database manually. But either way, here is our handsetdetection config:

```
return [
    'username' => env('HANDSETDETECTION_USERNAME'),
    'secret' => env('HANDSETDETECTION_PASSWORD'),
    'site_id' => env('HANDSETDETECTION_SITE_ID'),
    'use_local' => true,
    'filesdir' => storage_path('app'),
    'api_server' => 'api.handsetdetection.com',
    'cache_requests' => false,
];
```

Thank you for your assistance.
-Nik

**Comment by elricho** [comment]
Thanks for the info @djskripta. 

detect:devices tests 4 http headers. Did any of the 4 requests work ? or were they all {"status":301,"message":"Not Found"} ?

The config looks good. By way of a test : If you change the 'filesdir' to '/tmp/somedir' (fully pathed) then go through the process again (fetcharchive followed by detect:devices) do you get the same result ? .. trying to rule out pathing issues.

**Comment by djskripta** [comment]
Thanks for all of your help. 

Looks like this was indeed a permissions issue. After testing with `/tmp/somedir`, then setting permissions for `storage/app`, deleting `hd40store`, then retrying the process again with the original directory.. the `php artisan detect:devices` command worked as expected
